# Generated by Django 4.2.8 on 2024-01-31 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kriteria', '0009_alter_kriteria_bobot_kriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('bobot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kriteria.kriteria')),
                ('nilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nilai.nilai')),
            ],
        ),
    ]
