# Generated by Django 4.2.8 on 2024-01-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sapi',
            name='desc_sapi',
        ),
    ]
