# Generated by Django 4.2.8 on 2024-01-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapi', '0002_remove_sapi_desc_sapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapi',
            name='desc_sapi',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
