# Generated by Django 4.2.8 on 2024-02-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hasil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('tgl_pemilihan', models.DateField()),
            ],
        ),
    ]
