# Generated by Django 4.2.8 on 2024-03-10 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sapi', '0003_sapi_desc_sapi'),
        ('hasil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_Hasil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_norm', models.FloatField()),
                ('hasil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hasil.hasil')),
                ('sapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapi.sapi')),
            ],
        ),
    ]
