# Generated by Django 4.2.8 on 2023-12-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kriteria', models.CharField(max_length=50)),
                ('bobot_kriteria', models.FloatField()),
                ('satuan', models.FloatField()),
                ('atribut', models.CharField(max_length=20)),
            ],
        ),
    ]
