# Generated by Django 4.2.8 on 2023-12-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kriteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteria',
            name='bobot_kriteria',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='satuan',
            field=models.IntegerField(),
        ),
    ]
