# Generated by Django 4.2.8 on 2023-12-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kriteria', '0002_alter_kriteria_bobot_kriteria_alter_kriteria_satuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteria',
            name='bobot_kriteria',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='satuan',
            field=models.FloatField(),
        ),
    ]
