# Generated by Django 4.2.8 on 2023-12-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kriteria', '0003_alter_kriteria_bobot_kriteria_alter_kriteria_satuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteria',
            name='atribut',
            field=models.CharField(choices=[('benefit', 'benefit'), ('cost', 'cost')], max_length=20),
        ),
    ]
