# Generated by Django 4.2.8 on 2023-12-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kriteria', '0004_alter_kriteria_atribut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteria',
            name='atribut',
            field=models.CharField(max_length=20),
        ),
    ]
