# Generated by Django 4.2.8 on 2024-01-03 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sapi', '0001_initial'),
        ('kriteria', '0005_alter_kriteria_atribut'),
    ]

    operations = [
        migrations.CreateModel(
            name='KriteriaSapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('kriteria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kriteria.kriteria')),
                ('sapi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapi.sapi')),
            ],
        ),
    ]
