# Generated by Django 4.2.8 on 2024-01-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kriteria', '0006_kriteriasapi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kriteriasapi',
            old_name='kriteria_id',
            new_name='kriteria',
        ),
        migrations.RenameField(
            model_name='kriteriasapi',
            old_name='sapi_id',
            new_name='sapi',
        ),
    ]
