# Generated by Django 4.2.8 on 2024-01-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kriteria', '0007_rename_kriteria_id_kriteriasapi_kriteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteria',
            name='satuan',
            field=models.CharField(max_length=10),
        ),
    ]
