# Generated by Django 4.2.8 on 2024-01-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kriteria', '0008_alter_kriteria_satuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteria',
            name='bobot_kriteria',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
